{{- $fullName := include "api.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  env: {{ .Values.php.env | quote }}
  debug: {{ .Values.php.debug | quote }}
  cors-allow-origin: {{ .Values.php.corsAllowOrigin | quote }}
  {{ if .Values.varnish.enabled }}
  varnish-url: {{ if .Values.varnish.url }}{{ .Values.varnish.url | quote }}{{ else }}{{ printf "http://%s-varnish" $fullName }}{{ end }}
  {{ end }}
  trusted-hosts: {{ .Values.php.trustedHosts | quote }}
  trusted-proxies: {{ join "," .Values.php.trustedProxies }}
  mercure-publish-url: {{ printf "http://%s-mercure/.well-known/mercure" .Release.Name | quote }}
  mercure-subscribe-url: {{ printf "https://%s/.well-known/mercure" (index .Values.ingress.hosts 1).host | quote }}
  api-entrypoint-host: {{ (index .Values.ingress.hosts 0).host | quote }}
