{{- $fullName := include "api.fullname" . -}}
{{- $name := "cronjob" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- include "api.labels" $data | nindent 4 }}
spec:
  schedule: '0 0 * * *'
  jobTemplate:
    metadata:
      annotations:
          rollme: {{ randAlphaNum 5 | quote }}
    spec:
      template:
        spec:
          serviceAccountName: {{ include "api.serviceAccountName" . }}
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}-{{ $name }}
              image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.php.image.pullPolicy }}
              command: ['/bin/sh', '-c']
              args: ['composer install --prefer-dist --no-progress --no-suggest --no-interaction && bin/console doctrine:schema:drop --force --no-interaction && bin/console doctrine:migrations:version --delete --all --no-interaction && bin/console doctrine:migrations:migrate --no-interaction && bin/console hautelook:fixtures:load --no-interaction']
              env:
                - name: TRUSTED_HOSTS
                  valueFrom:
                    configMapKeyRef:
                      name: {{ $fullName }}
                      key: trusted-hosts
                - name: TRUSTED_PROXIES
                  valueFrom:
                    configMapKeyRef:
                      name: {{ $fullName }}
                      key: trusted-proxies
                - name: APP_ENV
                  value: "dev"
                - name: APP_DEBUG
                  valueFrom:
                    configMapKeyRef:
                      name: {{ $fullName }}
                      key: debug
                - name: CORS_ALLOW_ORIGIN
                  valueFrom:
                    configMapKeyRef:
                      name: {{ $fullName }}
                      key: cors-allow-origin
                - name: VARNISH_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ $fullName }}
                      key: varnish-url
                - name: APP_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ $fullName }}
                      key: secret
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ $fullName }}
                      key: database-url
                - name: MERCURE_PUBLISH_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ $fullName }}
                      key: mercure-publish-url
                - name: MERCURE_SUBSCRIBE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ $fullName }}
                      key: mercure-subscribe-url
                - name: MERCURE_JWT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ $fullName }}
                      key: mercure-jwt-token
                - name: JWT_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ $fullName }}
                      key: jwt-secret-key
                - name: JWT_PUBLIC_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ $fullName }}
                      key: jwt-public-key
                - name: JWT_PASSPHRASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ $fullName }}
                      key: jwt-passphrase
                - name: API_ENTRYPOINT_SCHEME
                  value: "https"
                - name: API_ENTRYPOINT_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: {{ $fullName }}
                      key: api-entrypoint-host
                - name: API_ENTRYPOINT_PORT
                  value: "443"
