stages:
  - build
  - deploy

.build_template_npm: &build_template_npm
  stage: build
  image: node:14
  variables:
    FILE_PATH
    FILE_CACHE_PATH
  script:
    - cd ${FILE_PATH}
    - npm ci --cache .npm --prefer-offline
    - npm run build --production
  rules:
    - changes:
        paths:
          - ${FILE_PATH}/**/*
  artifacts:
    paths:
      - ${FILE_PATH}/build
  cache:
    paths:
        - ${FILE_PATH}/.npm
    key:
      files:
        - ${FILE_PATH}/${FILE_CACHE_PATH}
  retry: 1
  interruptible: true

build_client:
  <<: *build_template_npm
  variables:
    FILE_PATH: client
    FILE_CACHE_FILE: package-lock.json

build_admin:
  <<: *build_template_npm
  variables:
    FILE_PATH: admin
    FILE_CACHE_FILE: package-lock.json

build_api:
  stage: build
  image: pockost/php:8.0-cli-bullseye
  script:
    - cd api
    - composer install --no-scripts
  cache: 
    paths:
      - api/vendor 
    key:
      files:
        - api/composer.lock 
        - api/composer.json 
  artifacts:
    paths:
      - api
    exclude:
      - api/test
      - api/tests/**/*
      - api/var
      - api/var/**/*
  rules:
    - changes:
        paths:
          - ${FILE_PATH}/**/*
  retry: 1
  interruptible: true
